set_pns_commit_mode true
# Starting to commit core rings
create_power_straps  -direction vertical  -start_at 883.140 -nets VDD -layer M8 -width 0.500 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 882.110 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 0.780 -nets VDD -layer M8 -width 0.500 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 882.110 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 1.050 -nets VDD -layer M9 -width 1.040 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 883.390 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 881.590 -nets VDD -layer M9 -width 1.040 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 883.390 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 882.400 -nets VSS -layer M8 -width 0.500 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 880.540 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 1.520 -nets VSS -layer M8 -width 0.500 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 880.540 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 2.620 -nets VSS -layer M9 -width 1.040 -start_low_ends coordinate  -start_low_ends_coordinate 1.270 -start_high_ends coordinate  -start_high_ends_coordinate 882.650 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 880.020 -nets VSS -layer M9 -width 1.040 -start_low_ends coordinate  -start_low_ends_coordinate 1.270 -start_high_ends coordinate  -start_high_ends_coordinate 882.650 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
# Starting to commit block rings
# Starting to commit metal8 straps for net VDD
create_power_straps  -direction vertical  -start_at 31.795 -nets VDD  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 882.110 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 58.675 -nets VDD  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 882.110 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 85.555 -nets VDD  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 882.110 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 116.275 -nets VDD  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 882.110 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 143.155 -nets VDD  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 882.110 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 170.035 -nets VDD  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 882.110 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 200.755 -nets VDD  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 882.110 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 227.635 -nets VDD  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 882.110 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 258.355 -nets VDD  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 882.110 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 285.235 -nets VDD  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 882.110 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 312.115 -nets VDD  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 882.110 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 342.835 -nets VDD  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 882.110 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 369.715 -nets VDD  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 882.110 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 400.435 -nets VDD  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 882.110 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 427.315 -nets VDD  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 882.110 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 454.195 -nets VDD  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 882.110 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 484.915 -nets VDD  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 882.110 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 511.795 -nets VDD  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 882.110 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 542.515 -nets VDD  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 882.110 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 569.395 -nets VDD  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 882.110 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 596.275 -nets VDD  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 882.110 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 626.995 -nets VDD  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 882.110 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 653.875 -nets VDD  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 882.110 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 684.595 -nets VDD  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 882.110 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 711.475 -nets VDD  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 882.110 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 738.355 -nets VDD  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 882.110 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 769.075 -nets VDD  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 882.110 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 795.955 -nets VDD  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 882.110 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 826.675 -nets VDD  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 882.110 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 853.555 -nets VDD  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 882.110 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal8 straps for net VSS
create_power_straps  -direction vertical  -start_at 32.285 -nets VSS  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 880.540 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 59.165 -nets VSS  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 880.540 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 86.045 -nets VSS  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 880.540 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 116.765 -nets VSS  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 880.540 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 143.645 -nets VSS  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 880.540 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 170.525 -nets VSS  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 880.540 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 201.245 -nets VSS  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 880.540 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 228.125 -nets VSS  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 880.540 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 258.845 -nets VSS  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 880.540 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 285.725 -nets VSS  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 880.540 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 312.605 -nets VSS  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 880.540 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 343.325 -nets VSS  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 880.540 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 370.205 -nets VSS  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 880.540 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 400.925 -nets VSS  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 880.540 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 427.805 -nets VSS  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 880.540 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 454.685 -nets VSS  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 880.540 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 485.405 -nets VSS  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 880.540 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 512.285 -nets VSS  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 880.540 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 543.005 -nets VSS  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 880.540 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 569.885 -nets VSS  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 880.540 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 596.765 -nets VSS  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 880.540 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 627.485 -nets VSS  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 880.540 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 654.365 -nets VSS  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 880.540 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 685.085 -nets VSS  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 880.540 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 711.965 -nets VSS  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 880.540 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 738.845 -nets VSS  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 880.540 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 769.565 -nets VSS  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 880.540 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 796.445 -nets VSS  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 880.540 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 827.165 -nets VSS  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 880.540 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 854.045 -nets VSS  -layer M8 -width 0.250 -pitch_within_group 28.390 -start_low_ends coordinate  -start_low_ends_coordinate 2.100 -start_high_ends coordinate  -start_high_ends_coordinate 880.540 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal9 straps for net VDD
create_power_straps  -direction horizontal  -start_at 30.070 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 883.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 60.790 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 883.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 86.390 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 883.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 117.110 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 883.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 142.710 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 883.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 173.430 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 883.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 199.030 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 883.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 229.750 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 883.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 255.350 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 883.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 286.070 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 883.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 311.670 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 883.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 342.390 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 883.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 367.990 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 883.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 398.710 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 883.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 424.310 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 883.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 455.030 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 883.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 480.630 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 883.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 511.350 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 883.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 542.070 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 883.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 567.670 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 883.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 598.390 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 883.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 623.990 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 883.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 654.710 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 883.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 680.310 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 883.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 711.030 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 883.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 736.630 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 883.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 767.350 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 883.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 792.950 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 883.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 823.670 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 883.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 849.270 -nets VDD  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 0.530 -start_high_ends coordinate  -start_high_ends_coordinate 883.390 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal9 straps for net VSS
create_power_straps  -direction horizontal  -start_at 31.130 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 1.270 -start_high_ends coordinate  -start_high_ends_coordinate 882.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 61.850 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 1.270 -start_high_ends coordinate  -start_high_ends_coordinate 882.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 87.450 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 1.270 -start_high_ends coordinate  -start_high_ends_coordinate 882.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 118.170 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 1.270 -start_high_ends coordinate  -start_high_ends_coordinate 882.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 143.770 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 1.270 -start_high_ends coordinate  -start_high_ends_coordinate 882.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 174.490 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 1.270 -start_high_ends coordinate  -start_high_ends_coordinate 882.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 200.090 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 1.270 -start_high_ends coordinate  -start_high_ends_coordinate 882.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 230.810 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 1.270 -start_high_ends coordinate  -start_high_ends_coordinate 882.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 256.410 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 1.270 -start_high_ends coordinate  -start_high_ends_coordinate 882.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 287.130 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 1.270 -start_high_ends coordinate  -start_high_ends_coordinate 882.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 312.730 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 1.270 -start_high_ends coordinate  -start_high_ends_coordinate 882.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 343.450 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 1.270 -start_high_ends coordinate  -start_high_ends_coordinate 882.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 369.050 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 1.270 -start_high_ends coordinate  -start_high_ends_coordinate 882.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 399.770 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 1.270 -start_high_ends coordinate  -start_high_ends_coordinate 882.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 425.370 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 1.270 -start_high_ends coordinate  -start_high_ends_coordinate 882.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 456.090 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 1.270 -start_high_ends coordinate  -start_high_ends_coordinate 882.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 481.690 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 1.270 -start_high_ends coordinate  -start_high_ends_coordinate 882.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 512.410 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 1.270 -start_high_ends coordinate  -start_high_ends_coordinate 882.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 543.130 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 1.270 -start_high_ends coordinate  -start_high_ends_coordinate 882.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 568.730 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 1.270 -start_high_ends coordinate  -start_high_ends_coordinate 882.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 599.450 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 1.270 -start_high_ends coordinate  -start_high_ends_coordinate 882.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 625.050 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 1.270 -start_high_ends coordinate  -start_high_ends_coordinate 882.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 655.770 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 1.270 -start_high_ends coordinate  -start_high_ends_coordinate 882.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 681.370 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 1.270 -start_high_ends coordinate  -start_high_ends_coordinate 882.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 712.090 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 1.270 -start_high_ends coordinate  -start_high_ends_coordinate 882.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 737.690 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 1.270 -start_high_ends coordinate  -start_high_ends_coordinate 882.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 768.410 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 1.270 -start_high_ends coordinate  -start_high_ends_coordinate 882.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 794.010 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 1.270 -start_high_ends coordinate  -start_high_ends_coordinate 882.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 824.730 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 1.270 -start_high_ends coordinate  -start_high_ends_coordinate 882.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 850.330 -nets VSS  -layer M9 -width 0.520 -pitch_within_group 28.270 -start_low_ends coordinate  -start_low_ends_coordinate 1.270 -start_high_ends coordinate  -start_high_ends_coordinate 882.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
set_pns_commit_mode false
